import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

export default function Home({ scroll }) {
  return (
    <>
      <style jsx>
        {`
          .saluteImage {
            transform: translate(${scroll * 0.4}px, ${scroll * 0.7}px);
          }
          .saluteText {
            transform: translateY(${scroll * 0.2}px);
          }
          .intro {
            transform: translateX(${scroll * 0.2}px);
          }
          .page3 {
            background-position-y: ${scroll * 0.5}px;
          }
          .job1 {
            transform: translateX(calc(200vh - ${scroll}px));
          }
          .page4 {
            background-position-y: ${-scroll * 0.5}px;
          }
          .job2 {
            transform: translateX(calc(-300vh + ${scroll}px));
          }
          .projectTitle {
            transform: translateY(calc(400vh - ${scroll}px));
          }
          .phoneScreen1 {
            transform: translateX(calc(520vh - ${scroll}px));
          }
          .laptopScreen {
            transform: translateX(calc(640vh - ${scroll}px));
          }
          .phoneScreen2 {
            transform: translateX(calc(770vh - ${scroll}px));
          }
          .findme {
            transform: translateY(calc(890vh - ${scroll}px));
          }
          .github {
            transform: translateX(calc(${scroll}px - 895vh));
          }
          .linkedin {
            transform: translateX(calc(-${scroll}px + 895vh));
          }
        `}
      </style>
      <Head>
        <title>Shahrukh - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container  flex bg-black min-w-full">
        <div className="page1 flex h-full overflow-hidden ">
          <div className="flex-3 saluteText flex-grow">
            <h1 className="saluteHead">Hi</h1>
          </div>
          <div className="saluteImage flex-1 flex-grow  object-bottom mb-0">
            <Image
              width={406}
              height={900}
              className="saluteImg"
              src="/person.png"
              alt=""
            />
          </div>
        </div>
        <div className="page2">
          <div className="intro">
            <p className="name purple">I'm Shahrukh</p>
          </div>
        </div>

        <div className="page3">
          <div className="job1">
            <p className="webdev">a Web Developer</p>
          </div>
        </div>
        <div className="page4">
          <div className="job2">
            <p className="gamedev">and Game Developer</p>
          </div>
        </div>
        {/* Projects */}

        <div className="projects">
          <h1 className="projectTitle">Here are some of my projects</h1>

          <div className="project">
            <div className="phoneScreen phoneScreen1">
              <Image width={300} height={600} src="/phone.png" alt="" />
              <div className="innerPhone">
                {/* <img src="" alt="innerphone" /> */}
              </div>
            </div>
            <div className="projectDescreption">
              <h1 className="projectHeading">Heading</h1>
              <div className="projectDescreptionInner">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
                  voluptatibus doloribus aut iusto non quas, officiis quia
                  nesciunt nihil recusandae laudantium impedit dignissimos quae,
                  distinctio, soluta harum. Laudantium eligendi animi impedit
                  omnis quam, temporibus numquam et soluta! Ullam ignissimos
                  quae, distinctio, soluta harum. Laudantium eligendi animi
                  impedit omnis quam, temporibus numquam et soluta! Ullam eaque
                  quos consequatur cupiditate?
                </p>
              </div>
              <div className="projectButton">
                <button className="btn">Read more</button>
              </div>
            </div>
          </div>

          <div className="project">
            <div className="phoneScreen laptopScreen">
              <Image width={600} height={379} src="/laptop.png" alt="" />
              <div className="innerPhone">
                {/* <img src="" alt="innerphone" /> */}
              </div>
            </div>
            <div className="projectDescreption">
              <h1 className="projectHeading">Heading</h1>
              <div className="projectDescreptionInner">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
                  voluptatibus doloribus aut iusto non quas, officiis quia
                  nesciunt nihil recusandae laudantium impedit dignissimos quae,
                  distinctio, soluta harum. Laudantium eligendi animi impedit
                  omnis quam, temporibus numquam et soluta! Ullam ignissimos
                  quae, distinctio, soluta harum. Laudantium eligendi animi
                  impedit omnis quam, temporibus numquam et soluta! Ullam eaque
                  quos consequatur cupiditate?
                </p>
              </div>
              <div className="projectButton">
                <button className="btn">Read more</button>
              </div>
            </div>
          </div>

          <div className="project">
            <div className="phoneScreen phoneScreen2">
              <Image width={300} height={600} src="/phone.png" alt="" />
              <div className="innerPhone">
                {/* <img src="" alt="innerphone" /> */}
              </div>
            </div>
            <div className="projectDescreption">
              <h1 className="projectHeading">Heading</h1>
              <div className="projectDescreptionInner">
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod
                  voluptatibus doloribus aut iusto non quas, officiis quia
                  nesciunt nihil recusandae laudantium impedit dignissimos quae,
                  distinctio, soluta harum. Laudantium eligendi animi impedit
                  omnis quam, temporibus numquam et soluta! Ullam ignissimos
                  quae, distinctio, soluta harum. Laudantium eligendi animi
                  impedit omnis quam, temporibus numquam et soluta! Ullam eaque
                  quos consequatur cupiditate?
                </p>
              </div>
              <div className="projectButton">
                <button className="btn">Read more</button>
              </div>
            </div>
          </div>
        </div>

        <div className="page6">
          <div className="findme">
            <h5>Connect with me 🙂</h5>{" "}
          </div>
          <div className="socialIcons">
            <div className="github">
              <Link target="_blank" href="https://github.com/Shahrukh-10">
                <Image
                  className="icon"
                  width={80}
                  height={80}
                  src="/github.png"
                  alt=""
                />
              </Link>
            </div>
            <div className="linkedin">
              <Link
                target="_blank"
                href="https://www.linkedin.com/in/shahrukh-khan-0344391a2"
              >
                <Image
                  className="icon"
                  width={80}
                  height={80}
                  src="/linkedin.png"
                  alt=""
                />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
